export const NavLinkApi = [
  { links: "Model S" },
  { links: "Model 3" },
  { links: "Model X" },
  { links: "Model Y" },
  { links: "Solar Roof" },
  { links: "Solar Panels" },
  { links: "Existing Inventiry" },
  { links: "Trade In" },
  { links: "Test Drive" },
  { links: "Powerwall" },
  { links: "Commercial Energy" },
  { links: "Utilities" },
  { links: "Charging" },
  { links: "Find US" },
  { links: "Support" },
  { links: "Careers" },
  { links: "Shop" },
  { links: "Account" },
  { links: "More" },
];
